export {
  BUILD_SHELL_VERSION,
  type BuildShell,
  type BuildShellObstacle,
  type BuildShellRoomWriter,
  type LayoutSnapshotForBuildShell,
  applyBuildShell,
  buildShellFromLayoutSnapshot,
  buildShellFromLegacyPlaySpaceLayout,
  joinSpawnIsPassable,
} from "./buildShell.js";
export {
  DEFAULT_TEMPLATE_DISPLAY_NAME,
  type PlaySpaceTemplateRecord,
  _resetPlaySpaceTemplateStoreForTests,
  bootstrapDefaultPlaySpaceTemplateIfEmpty,
  createPlaySpaceTemplate,
  getDefaultPlaySpaceTemplate,
  getPlaySpaceTemplate,
  initPlaySpaceTemplateStore,
  isTemplateSourceRoomAvailable,
  isValidPlaySpaceTemplateSourceRoom,
  listPlaySpaceTemplates,
  loadPlaySpaceTemplateStore,
  reassignPlaySpaceTemplateSource,
  resolveTemplateIdForPlaySpaceCreate,
  resyncPlaySpaceTemplate,
  setDefaultPlaySpaceTemplate,
  setPlaySpaceTemplateArchived,
  updatePlaySpaceTemplateMetadata,
  wireTemplateForTests,
} from "./store.js";
